export const SVG_CONTAINER_ELEMENTS =
  {
    // http://www.w3.org/TR/SVG/intro.html#TermContainerElement
    a: true,
    defs: true,
    glyph: true,
    g: true,
    marker: true,
    mask: true,
    'missing-glyph': true,
    pattern: true,
    svg: true,
    switch: true,
    symbol: true,
    text: true,

    // http://www.w3.org/TR/SVG/intro.html#TermDescriptiveElement
    desc: true,
    metadata: true,
    title: true,
  }

// http://www.w3.org/html/wg/drafts/html/master/syntax.html#void-elements
export const SELF_CLOSING_ELEMENTS =
  {
    area: true,
    base: true,
    br: true,
    col: true,
    embed: true,
    hr: true,
    img: true,
    input: true,
    keygen: true,
    link: true,
    meta: true,
    param: true,
    source: true,
    track: true,
    wbr: true,
  }

export const PROPERTIES_TO_SKIP: ReadonlyArray<string> = [
  'class',
  'focus',
  'style',
  'attrs',
  'key',
  'module',
  'init',
  'create',
  'update',
  'insert',
  'remove',
  'destroy',
  'prepatch',
  'postpatch',

  'attributes',
  'childElementCount',
  'children',
  'classList',
  'clientHeight',
  'clientLeft',
  'clientTop',
  'clientWidth',
  'currentStyle',
  'firstElementChild',
  'innerHTML',
  'lastElementChild',
  'nextElementSibling',
  'ongotpointercapture',
  'onlostpointercapture',
  'onwheel',
  'outerHTML',
  'previousElementSibling',
  'runtimeStyle',
  'scrollHeight',
  'scrollLeft',
  'scrollLeftMax',
  'scrollTop',
  'scrollTopMax',
  'scrollWidth',
  'tabStop',
  'tagName',
]
